<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>WindowsPeace.Tools.DiskDump</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WindowsPeace.Core\WindowsPeace.Core.csproj" />
  </ItemGroup>
</Project>
